db_path="/home/dennis/code/marmot/pb_10a/pb_data/data.db"
node_id=1
seq_map_path="/tmp/seq-map-1.cbor"

[snapshot]
enabled=true
store="nats"

[snapshot.nats]
replicas=1

[replication_log]
replicas=1
shards=1
max_entries=1024
compress=true


[nats]
urls=[
    "nats://localhost:4222"
]
subject_prefix="marmot-change-log"
stream_prefix="marmot-changes"


[logging]
verbose=true
format="console"
